What is Ndarray?

An ndarray (N- dimensional array) is a multidimensional container of items of the same type and size. It allows u to perform operations on large dataset effeciently.

In [2]:
import numpy as np

# Creating a 1D array
array_1d = np.array([1,2,3,4,5])
print("1D Array:", array_1d)

# Creating a 2D array
array_2d = np.array([[1,2,3],[4,5,6]])
print("2D Array:\n", array_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [4]:
# Creating a 2D array of all zeros

zeros_array = np.zeros((3,4))   # 3 rows and 4 column
print("Aray of Zeros:\n",zeros_array)


Aray of Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
# Creating a 2D array of all ones

ones_array = np.ones(5)
print("Array of ones:\n",ones_array)


Array of ones:
 [1. 1. 1. 1. 1.]


In [6]:
# Creating an arrays with value from 0 to 9

range_array = np.arange(10)
print("Range Array:", range_array)


Range Array: [0 1 2 3 4 5 6 7 8 9]


In [7]:
# Creating an array with 5 evenly spaced value between 0 and 1

linspace_array = np.linspace(0, 1, 5)
print("Linspace Array:",linspace_array)


Linspace Array: [0.   0.25 0.5  0.75 1.  ]


In [8]:
print("Shape of array_2d", array_2d.shape)
print("Size of array_2d", array_2d.size)


Shape of array_2d (2, 3)
Size of array_2d 6


In [9]:
print("Data type of array_2d:", array_2d.dtype)

Data type of array_2d: int64
