Indexing with NumPy Arrays

Indexing allows you to access and manipulate specific elements with NumPy arrays. This notebook will guide u through Indexing for both 1D and 2D arrays.


In [1]:
import numpy as np

# 1. Indexing

In [2]:
# Creating a 1D array
array_1d = np.array([10,20,30,40,50])

# Accessing the 3rd element (index 2)
print("Element at index 2:", array_1d[2])

Element at index 2: 30


In [3]:
# Accessing the last element using negative indexig
print("Last element:", array_1d[-1])

# Accessing the second-to-last element
print("Second element:", array_1d[-2])


Last element: 50
Second element: 40


In [4]:
# Creatinfd 2D array
array_2d =np.array([[10,20,30],[40,50,60]])

#Accessing the element at row 1,column 2
print("Element at (1,2):", array_2d[1,2])

Element at (1,2): 60


In [5]:
# Accessing the second row
print("Second row:", array_2d[1])

# Accessing the first column
print("First column:", array_2d[:,0])

Second row: [40 50 60]
First column: [10 40]


In [6]:
# Boolean indexing to select elements greater than 30
boolean_index = array_2d[array_2d > 30]
print("Element greater than 30:", boolean_index)

Element greater than 30: [40 50 60]


In [7]:
# Integer array indexing
print("Elements at indices 0 and 2 of the first row:", array_2d[0,[0,2]])

Elements at indices 0 and 2 of the first row: [10 30]


# 2. Slicing

In [8]:
# Creating a 1D array
array_1d = np.array([10,20,30,40,50])

# Slicing elements fromindex 1 to 3
slice_1d = array_1d[1:4]
print("Sliced 1D Array (0:5:2):", slice_1d)


Sliced 1D Array (0:5:2): [20 30 40]


In [9]:
# Slicing elements fom index 0 to 4 with a step of 2
slice_step_1d = array_1d[0:5:2]
print("Sliced 1D Array (0:5:2):", slice_step_1d)


Sliced 1D Array (0:5:2): [10 30 50]


In [10]:
# Creating a 2D array
array_2d = np.array([[10,20,30],[40,50,60],[70,80,90]])

# Slicing a sub-array from the first two rows and columns
slice_2d = array_2d[:2,:2]
print("Sliced 2D Array:\n", slice_2d)

Sliced 2D Array:
 [[10 20]
 [40 50]]


In [11]:
# Slicing the first 2 rows
rows_2d = array_2d[:2]
print("Firsttwo rows:\n", rows_2d)

# Slicing the last columns
last_column_2d = array_2d[:,-1]
print("Last column:",last_column_2d)

Firsttwo rows:
 [[10 20 30]
 [40 50 60]]
Last column: [30 60 90]


In [12]:
# Slicing every other row
step_rows_2d = array_2d[::2]
print("Every other row:\n",step_rows_2d)

# Slicing every other column
step_columns_2d = array_2d[:,::2]
print("Every otherColumn:\n", step_columns_2d)


Every other row:
 [[10 20 30]
 [70 80 90]]
Every otherColumn:
 [[10 30]
 [40 60]
 [70 90]]
